services:
  tour-2025-fe-service:
    image: node:24
    container_name: tour-2025-fe-service
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5173:5173
    command: sh -c "npm install && npm run dev"