export { default as Dashboard } from './Dashboard'
export { default as MCQs } from './MCQs'
export { default as Puzzles } from './Puzzles'
export { default as Teams } from './Teams'
export { default as Settings } from './Settings'
export { default as Monitor } from './Monitor'
export { default as Launch } from './Launch'
